name: Insomnia CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0
      - name: Run test suites
        run: inso run test --verbose